### ISSUE TITLE
Topics Widget are too big

### ISSUE THREAD

**Issue by behelpbg** [inventea/we_clearblue#12]
**phpBB version:** 3.2.8
**Style version:** 3.1.9
**Link to your forum (optional):**
**Have you modified source files?** No
**Browser and version:** Chrome last updated
**Issue description:** Topic widget is too big
Screenshot https://prnt.sc/phzonz

**Comment by jpustula** [comment]
Hi! Where did you download the style? I don't develop it anymore (last version was for phpBB 3.0.x) but there are some forks compatible with newer phpBB versions. I suggest looking for help/filling a bug report for current author.
