### ISSUE TITLE
Plan for phpBB 3.1.*

### ISSUE THREAD

**Issue by seanieb** [inventea/we_clearblue#3]
Whats the plan/timeline for a phpBB 3.1.* compatible version? 

Thanks!

**Comment by jaroslw** [comment]
For sure it will be released. Unfortunately I can't give you any specified date. I think it should be ready at the end of February. I'll start working on we_clearblue after finishing we_universal.

**Comment by seanieb** [comment]
Cool, Thank you.

Would it be possible to document, at a high level, the migration process for we_universal? 
I've searched for a good guide to migrate theme's and I haven't found anything. I'd love to help you migrate we_clearblue (If I can find the time).

**Comment by jaroslw** [comment]
What would you like to read in documentation? Unfortunately the update won't be an easy step by step process for heavy customised styles. Changes in the code are quite big (mostly because of new features available).

**Comment by seanieb** [comment]
> Unfortunately the update won't be an easy step by step process for heavy customised styles.

Cool, yeah probably not the best use of time if it doesn't result in anything that can be reused. No biggie. Let me know if there is anything I can help with. 

Thanks again.

**Comment by jaroslw** [comment]
That changes are mostly related to new extensions system from phpBB 3.1. I couldn't omit them :) Second bigger change is theme inheritance. I think is was worth. There are no more prosilver CSS files distributed with the style - they're inherited directly from prosilver's directory. Also huge custom CSS file (we_universal.css/we_clearblue.css) was split into separate modules (files).

**Comment by seanieb** [comment]
Any update on this? It's cool if you can't do it, I'd just like to know so I can plan moving themes. Thanks.
