### ISSUE TITLE
View profile error

### ISSUE THREAD

**Issue by AlexanderMars** [inventea/we_clearblue#4]
Not able to view any member profiles from: http://forum.seattleus.com/memberlist.php or http://forum.seattleus.com/index.php

"Parse error: syntax error, unexpected $end in /home/richisle/seattleus.com/forum/cache/tpl_we-clearblue_memberlist_view.html.php on line 109"

**Comment by jaroslw** [comment]
Did you modified anything in templates? Try reupload memberlist_view.html and purge forum cache.

**Comment by AlexanderMars** [comment]
That works, thank you! 

Everything looks good now except a member profile icons: http://forum.seattleus.com/memberlist.php such as: send a private message / web / send email They are not displayed. What could be a reason of this? Thx.
